version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 8000:3000
      - 9229:9229
    depends_on: 
      - redis
      - postgres

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/var/lib/redis/data/
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis

  postgres:
    image: postgres
    restart: always
    container_name: postgres_container
    env_file:
      - local.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4:4.18
    env_file:
      - local.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data/
    ports:
      - 80:80
    depends_on:
      - postgres

volumes:
    database-data:
    pgadmin-data:
    redis-data: